name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push Gateway
      - name: Build & Push Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest

      # Build & Push Auth Service
      - name: Build & Push Auth Service
        uses: docker/build-push-action@v4
        with:
          context: ./auth-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

      # Build & Push User Service
      - name: Build & Push User Service
        uses: docker/build-push-action@v4
        with:
          context: ./user-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest

      # Build & Push Account Service
      - name: Build & Push Account Service
        uses: docker/build-push-action@v4
        with:
          context: ./account-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/account-service:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout Config
        uses: actions/checkout@v3

      - name: Login to Docker Hub (on Local)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make script executable
        run: chmod +x deploy.sh

      - name: Run Deployment Script
        run: ./deploy.sh "${{ secrets.PROJECT_DIR }}"