name: CI/CD Pipeline for gateway service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run without making changes'
        type: boolean
        default: false

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      gateway: ${{ steps.filter.outputs.gateway == 'true' || github.event.inputs.dry_run == 'true' }}
    steps:
    - uses: actions/checkout@v5
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          gateway:
            - "services/api-gateway/**"

  build-and-push:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.gateway == 'true' && github.event.inputs.dry_run != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push gateway Service
      - name: Build & Push gateway Service
        if: ${{ needs.check-changes.outputs.gateway == 'true' }}
        uses: docker/build-push-action@v4
        with:
          context: ./services/gateway-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gateway-service:v1

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout Config
        uses: actions/checkout@v5

      - name: Login to Docker Hub (on Local)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make script executable
        run: chmod +x ./scripts/deploy-per-service.sh

      - name: Run Deployment Script
        run: ./scripts/deploy-per-service.sh "${{ secrets.PROJECT_DIR }}" "api-gateway"