name: CI/CD Pipeline for user service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run without making changes'
        type: boolean
        default: false

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      user: ${{ steps.filter.outputs.user == 'true' || github.event.inputs.dry_run == 'true' }}
    steps:
    - uses: actions/checkout@v5
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          user:
            - "services/user-service/**"

  test-user:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.user == 'true' }}
    runs-on: self-hosted
    env:
      USERS_USER: ${{ secrets.USERS_USER }}
      USERS_PASSWORD: ${{ secrets.USERS_PASSWORD }}
      USERS_DB: ${{ secrets.USERS_DB }}
    steps: 
      - uses: actions/checkout@v5
      - run: chmod +x ./scripts/smoke-test-user.sh
      - run: ./scripts/smoke-test-user.sh

  build-and-push:
    needs: [check-changes, test-user]
    if: ${{ needs.check-changes.outputs.user == 'true' && github.event.inputs.dry_run != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push user Service
      - name: Build & Push user Service
        if: ${{ needs.check-changes.outputs.user == 'true' }}
        uses: docker/build-push-action@v4
        with:
          context: ./services/user-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:v1

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout Config
        uses: actions/checkout@v5

      - name: Login to Docker Hub (on Local)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make script executable
        run: chmod +x ./scripts/deploy-per-service.sh

      - name: Run Deployment Script
        run: ./scripts/deploy-per-service.sh "${{ secrets.PROJECT_DIR }}" "user-service"